### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by pellared**
## Why

https://github.com/signalfx/gdi-specification/issues/173

## What

This is the first stable release of the Splunk Distribution of OpenTelemetry Go
which is compliant with [Splunk's GDI Specification v1.3.0](https://github.com/signalfx/gdi-specification/tree/v1.3.0).

Please note that although the distribution is marked as stable,
some of its dependent components (e.g. `otelhttp` instrumentation library)
are still experimental.

This release uses [OpenTelemetry Go v1.7.0][otel-v1.7.0] and
[OpenTelemetry Go Contrib v1.7.0/v0.32.0][contrib-v1.7.0].

[otel-v1.7.0]: https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.7.0
[contrib-v1.7.0]: https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.7.0

### CODE REVIEW

**Review by MrAlias — COMMENTED** [review]
Which instrumentation libraries are stable and which are still experimental? Do we communicate this somewhere?

**Comment by pellared** [comment]
> Which instrumentation libraries are stable and which are still experimental? Do we communicate this somewhere?

Our only communication is the version number which I find "idiomatic" (I personally think it is good enough and easy to maintain).

AFAIK at the moment, all instrumentation from this repo would become stable and all from OTel Go Contrib would be experimental.

**Comment by pellared** [comment]
Moreover, I do not find it necessary to communicate the supported library version for a given instrumentation library.

**Comment by MrAlias** [comment]
> 

Gotcha, I misunderstood the changelog entry. I thought it was saying not all instrumentation libraries found here are stable. Please disregard.

**Review by MrAlias — APPROVED** [review]

**Pull request merged**
