### PR TITLE
Update Kafka attributes to align semconv v1.17.0

### PR DESCRIPTION
**Pull request by flf2ko**
as title

### CODE REVIEW

**Review by pellared — APPROVED** [review]
@MrAlias PTAL

**Comment by pellared** [comment]
First of all, thanks a lot for your PR 🙇 

1. Can you please add an entry in `CHANGELOG.md`?

2. Per [our contribution policy](https://github.com/signalfx/splunk-otel-go/blob/main/CONTRIBUTING.md#licensing) we need to ask you to sign our CLA. Can you please fill and submit the following form: https://www.splunk.com/en_us/form/contributions.html? Please let us know when you do so.

**Comment by pellared** [comment]
@flf2ko Also the [commits need to be signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

**Comment by pellared** [comment]
@flf2ko Are there any chances that you:

1. Sign the CLA (required)
2. Sign the commit (required)
3. Update the changelog (optional)?

**Comment by flf2ko** [comment]
Sorry for updating late.
All three actions should be done, and code base rebased.
Please let me know if there is any issue, thanks

**Review by pellared — APPROVED** [review]

**Comment by pellared** [comment]
@flf2ko, thank you for your contribution ❤️ 🎉

**Pull request merged**
